@extends('layouts.app')

@section('content')

<div class="inner-banner">
  <div class="container">
    <h3>FAQ</h3>
  </div>
</div>



<!--Start Part-1-->

<section id="part_1" style="min-height:600px">
  <div class="container">

    <h4 class="main-head">Frequently Asked Questions </h4>

    <section class="faq-det">

      <div class="container">
        <div class="faq-area row">
          <div class="col-md-8 faq-min">
            <div class="pogramsArea">

              <ul>
                <li class="same" id="tab-1"><a class="tabActive" id="atab-1" href="javascript:void(0)">What is a Masternode?  <span class="icon"> <i class="fas fa-minus"></i></span></a>
                  <div id="1stslide-1" class="openSlide">
                    <p>

                      Masternodes are dedicated servers on the Internet that enable instant transactions and perform the trust-less anonymization of users' funds. They usually get majority of the rewards per block for this task. </p>

                      <p>Masternodes are essentially addresses with a lot of coins in them that are not moved for extended periods of time. They help in securing the whole network and help stabilize the price of the coin, somewhat, by taking large number of coins out of circulation.
                      </p>
                    </div>
                  </li>
                  <li class="same" id="tab-2"><a class="tabinActive" id="atab-2" href="javascript:void(0)">What is a Shared Masternode?	 <span class="icon"> <i class="fas fa-plus"></i></span></a>
                    <div id="1stslide-2" class="openSlide" style="display:none;">
                      <p>To make a Masternode, it takes a lot of coins; worth a lot of money; and not everyone can afford it or want to put a lot of money into just a single coin. To get around this, several coin holders come together and pool their coins together and take part of the rewards, this is known as a Shared Masternode.</p>
                    </div>
                  </li>
                  <li class="same" id="tab-3"><a class="tabinActive" id="atab-3" href="javascript:void(0)">How does your Shared Masternode work? <span class="icon"> <i class="fas fa-plus"></i></span></a>
                    <div id="1stslide-3" class="openSlide" style="display:none;">
                      <p>

                        The total number of coins needed for a Masternode are divided equally into a certain number of Seats and people can essentially buy those Seats to take part in a Masternode for as low as a tenth of the total coins needed for a solo Masternode. </p>

                        <p>Each Seat has an equal share in the rewards generated by the Masternode. </p>

                        <p>When all the Seats are filled, the Masternode is started. </p>

                      </div>
                    </li>

                    <li class="same" id="tab-4"><a class="tabinActive" id="atab-3" href="javascript:void(0)">How can I trust MNCenter.online with my Coins?<span class="icon"> <i class="fas fa-plus"></i></span></a>
                      <div id="1stslide-4" class="openSlide" style="display:none;">
                        <p>

                          MNCenter.online is relatively 'new' however, our system is very transparent and automated . All of our users can track and monitor the rewards for each of the Masternode and get rewards paid out weekly,every Sunday. </p>

                          <p>The system is automated so this prevents 'many hands' getting involved or any manual movements of funds hence, the risk of anyone stealing funds are greatly reduced. </p>

                          <p>The service is also delivered through the website not another "Discord run Shared Masternode service", so we can be tracked and traced through the services we have registered  for in order to run the website. This means we have to provide more information to various services providers so that we can run the website in a smooth and secure way, unlike a typical "Discord Shared Masternode service" which is run by a user with a Discord account!
                          </p>
                        </div>
                      </li>

                      <li class="same" id="tab-5"><a class="tabinActive" id="atab-3" href="javascript:void(0)">How do I start using MNCenter.online? <span class="icon"> <i class="fas fa-plus"></i></span></a>
                        <div id="1stslide-5" class="openSlide" style="display:none;">
                          <p>
                            MNCenter.online is a share Masternode service. To start using the Shared Masternode services, you need to register  for an account via Account > Register.
                          </p>
                        </div>
                      </li>
                    </ul>

                  </div>

                </div>
                <div class="col-md-4 faq-img">
                  <img src="img/faq-img.png" alt="faq-img">
                </div>
              </div>
            </div>

          </section>



        </div>
        <div class="clearfix"></div>
      </section>


      <script>
      $(document).ready(function(){
        $(".same").click(function(){
          var sliderid = $(this).attr("id");

          var n = sliderid.split('-');
          var indid = (n[1]);

          $( ".openSlide" ).slideUp( "fast", function() {
            $( ".tabActive" ).removeClass( "tabActive" );

          });

          $( "#1stslide-" + indid ).slideDown( "fast", function() {
            $( "#atab-" + indid ).removeClass( "tabinActive").addClass("tabActive");
          });
        });
      });
    </script>
    <script type="text/javascript">
    // $(function(){
    // SyntaxHighlighter.all();
    // });
    $(window).load(function(){
      $('.flexslider').flexslider({
        animation: "fade",
        start: function(slider){
          $('body').removeClass('loading');
        }
      });

      $('ul.nav li.dropdown').hover(function() {
        $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeIn(500);
      }, function() {
        $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeOut(500);
      });
    });
  </script>

  @endsection
